packageExtensions:
  '@ant-design/plots@*':
    dependencies:
      '@antv/scale': '*'
      '@antv/util': '*'
  '@antv/attr@*':
    dependencies:
      '@antv/scale': '*'
  '@antv/g2plot@*':
    dependencies:
      '@antv/color-util': '*'
      '@antv/matrix-util': '*'
      '@antv/path-util': '*'
      '@antv/scale': '*'
      '@antv/util': '*'
  next@*:
    dependencies:
      '@next/env': '*'
      webpack: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.3.0.cjs
