# packageExtensions:
#   '@ant-design/plots@*':
#     dependencies:
#       '@antv/scale': '*'
#       '@antv/util': '*'
#   '@antv/attr@*':
#     dependencies:
#       '@antv/scale': '*'
#   '@antv/g2plot@*':
#     dependencies:
#       '@antv/color-util': '*'
#       '@antv/matrix-util': '*'
#       '@antv/path-util': '*'
#       '@antv/scale': '*'
#       '@antv/util': '*'
#   next@*:
#     dependencies:
#       '@next/env': '*'
#       webpack: '*'
#   'sst@*':
#     dependencies:
#       '@aws-sdk/types': '*'
#   'sst-aws-cdk@*':
#     dependencies:
#       '@aws-cdk/cx-api': '*'
#       'aws-sdk': '*'
#       'fs-extra': '*'
#       '@aws-cdk/cloud-assembly-schema': '*'
#       '@aws-cdk/cloudformation-diff': '*'
#       'cdk-assets': '*'

# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#     spec: '@yarnpkg/plugin-typescript'

pnpEnableEsmLoader: true
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.3.0.cjs
